/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentación;

import Dominio.Jugador;
import Presentación.MenuPrincipal;
import Presentación.PantallaPartida;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Frame o pantalla de Iniciar Partida, donde un usuario introduce su nickname y
 * el monto de apuesta, además cuenta con la opción de dirigirse a la pantalla
 * de configurar partida.
 *
 * @author Carlos A. Valle Encinas - David Sotelo Palafox Equipo#6
 */
public class MenuIniciaPartida extends javax.swing.JFrame {
Fondo fondo=new Fondo();  
    /**
     * Constructor del Frame.
     */
    public MenuIniciaPartida() {
        this.setContentPane(fondo);  
        initComponents();
        tamañoConfig(); 
    }

    /**
     * Método tamañoConfig el cual permite ajustar el tamaño del icono
     * configuración ubicado en el botón btnConfig.
     */
    public void tamañoConfig() {
        ImageIcon play;
        play = new ImageIcon(getClass().getResource("/img/config.png"));
        Icon png = new ImageIcon(play.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        ConfigurarPartida.setIcon(png);
    }

    /**
     * Método validaNombre que realiza las validaciones principales para el nick
     * del usuario tales como el tamaño de caracteres y que solo se permitan
     * alfanuméricos.
     *
     * @param evt: Evento al que escucha.
     */
    public void validaNombre(java.awt.event.KeyEvent evt){
        validaNombre.getText().trim();
        if(validaNombre.getText().length()>12)
        {
           evt.consume();
           int msg=1;
           mostrarError(msg);
        }
        char car= evt.getKeyChar();
        if(Character.isLetterOrDigit(car)){
           
        } 
        else
        {
           evt.consume();
           getToolkit().beep();
        }
    }


    /**
     * Método mostrarError que recibe como parametro un entero con el tipo de
     * error dependiendo el campo de texto que se esta validando.
     *
     * @param msg: Tipo mensaje.
     */
    public void mostrarError(int msg)
    {
       if(msg==1)
       {
        JOptionPane.showMessageDialog(null, "Solo se permiten como máximo 12 caracteres alfanuméricos", 
        "¡Mensaje de Advertencia!", JOptionPane.WARNING_MESSAGE);
       }
       if(msg==2)
       {
         JOptionPane.showMessageDialog(null, "Solo se permiten como máximo 6 caracteres numéricos", 
        "¡Mensaje de Advertencia!", JOptionPane.WARNING_MESSAGE);
       }
       if(msg==3)
       {
         JOptionPane.showMessageDialog(null, "Al parecer se le ha olvidado rellenar un campo!", 
        "¡Mensaje de Error!", JOptionPane.ERROR_MESSAGE);
       }
    }
    
    /**
     * Método que permite al usuario volver al Menu Principal.
     *
     * @param evt: Evento al que escucha.
     */
    public void volverMenuPrincipal(java.awt.event.ActionEvent evt){
      MenuPrincipal principal=new MenuPrincipal();
      principal.setVisible(true);
      this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validaNombre = new javax.swing.JTextField();
        volverMenuPrincipal = new javax.swing.JButton();
        ConfigurarPartida = new javax.swing.JButton();
        lblInicia = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        validaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validaNombreActionPerformed(evt);
            }
        });
        validaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                validaNombreKeyTyped(evt);
            }
        });

        volverMenuPrincipal.setBackground(new java.awt.Color(204, 255, 255));
        volverMenuPrincipal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        volverMenuPrincipal.setForeground(new java.awt.Color(102, 51, 0));
        volverMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        volverMenuPrincipal.setText("Volver");
        volverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMenuPrincipalActionPerformed(evt);
            }
        });

        ConfigurarPartida.setBackground(new java.awt.Color(204, 255, 255));
        ConfigurarPartida.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        ConfigurarPartida.setForeground(new java.awt.Color(102, 51, 0));
        ConfigurarPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/config.png"))); // NOI18N
        ConfigurarPartida.setText("Configurar Partida");
        ConfigurarPartida.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ConfigurarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigurarPartidaActionPerformed(evt);
            }
        });

        lblInicia.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        lblInicia.setForeground(new java.awt.Color(255, 255, 255));
        lblInicia.setText("Iniciar Partida");

        lblNombre1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre1.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(lblNombre1)
                .addGap(18, 18, 18)
                .addComponent(validaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblInicia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(volverMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(ConfigurarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInicia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfigurarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Métdo oyente que llama al método volverMenuPrincipal.
     *
     * @param evt: Evento al que escucha.
     */
    private void volverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMenuPrincipalActionPerformed
        // TODO add your handling code here:
       volverMenuPrincipal(evt);
    }//GEN-LAST:event_volverMenuPrincipalActionPerformed

    /**
     * Método oyente que muestra la pantalla de MenuConfigurar.
     *
     * @param evt: Evento al que escucha.
     */
    private void ConfigurarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigurarPartidaActionPerformed
        // TODO add your handling code here:
        
        if (validaNombre.getText().isEmpty()) {
            int msg = 3;
            mostrarError(msg);
        } else {
            MenuConfigurar menu=new MenuConfigurar();
            menu.setVisible(true);
            this.dispose();
        }
         
    }//GEN-LAST:event_ConfigurarPartidaActionPerformed

    /**
     * Método oyente de validaNombreKeyTyped que llama al método validaNombre.
     *
     * @param evt: Evento al que escucha.
     */
    private void validaNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validaNombreKeyTyped
        // TODO add your handling code here:
       validaNombre(evt);
    }//GEN-LAST:event_validaNombreKeyTyped

    private void validaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validaNombreActionPerformed
        // TODO add your handling code here: 
 
    }//GEN-LAST:event_validaNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfigurarPartida;
    private javax.swing.JLabel lblInicia;
    private javax.swing.JLabel lblNombre1;
    public javax.swing.JTextField validaNombre;
    private javax.swing.JButton volverMenuPrincipal;
    // End of variables declaration//GEN-END:variables
 
}
