/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentación;



import Diseño.CasillaEspecial;
import Diseño.CasillaNormal;
import Diseño.Dibujado;
import Dominio.Tablero;
import Lógica.EventosJugador;
import Lógica.FachadaLogica;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Frame o pantalla de Pantalla Partida, donde se muestra el tablero y es donde
 * los jugadores disfrutarán de la partida.
 *
 * @author Carlos A. Valle Encinas - David Sotelo Palafox Equipo#6
 */
public class PantallaPartida extends javax.swing.JFrame {

    private Tablero tablero;
    MenuPrincipal menuP=new MenuPrincipal();
    int puertoOrigen, puertoDestino;
    Fondo fondo = new Fondo();
    private FachadaLogica fachadaL;

    /**
     * Constructor del frame.
     */
    public PantallaPartida() {
        this.setContentPane(fondo);
        initComponents();
        tirarCañas.setEnabled(false);
    }

    /**
     * Método que permite ingresar en un txt la apuesta configurada.
     *
     * @param cantidad cantidad de la apuesta.
     */
    public void verificaApuesta(int cantidad) {
        String cadena = Integer.toString(cantidad);
        txtMontoA.setText(cadena);
        txtMontoA.setEditable(false);
    }

     public void iniciarPartida(){
        fachadaL= new FachadaLogica();
    }

    
   
    /**
     * Método salir partida que llama al método mensajeConfirmación y verifica
     * si el jugador existe.
     *
     * @param evt: Evento al que escucha.
     */
    public void salirPartida(java.awt.event.ActionEvent evt){
       int msg=2;
       mensajeConfirmación(msg);
    }
    /**
     * Método mensajeConfirmación que despliega un mensaje al usuario
     * preguntandole si desea empezar la partida o si desea abandonarla.
     *
     */
    public void mensajeConfirmación(int msg) {
      if(msg==2)
      {
         int op=JOptionPane.showConfirmDialog(this, "¿Esta seguro de abandonar la partida?", "Abandonar Partida", 0, JOptionPane.QUESTION_MESSAGE); 
         if (op == 0) {
            MenuPrincipal principal = new MenuPrincipal();
            principal.setVisible(true);
            this.dispose();
        }
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        panelTablero = new Diseño.EditorGráfico();
        lb2 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        btnSalirPartida = new javax.swing.JButton();
        tirarCañas = new javax.swing.JButton();
        empezarPartida = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMontoA = new javax.swing.JTextField();
        nombreJugador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caña 2.png"))); // NOI18N

        lb4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caña 2.png"))); // NOI18N

        lb3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Caña 1.png"))); // NOI18N

        panelTablero.setOpaque(false);

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );

        lb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caña 2.png"))); // NOI18N

        lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Caña 1.png"))); // NOI18N

        btnSalirPartida.setBackground(new java.awt.Color(204, 255, 255));
        btnSalirPartida.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnSalirPartida.setForeground(new java.awt.Color(102, 51, 0));
        btnSalirPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log_out.png"))); // NOI18N
        btnSalirPartida.setText("Salir Partida");
        btnSalirPartida.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSalirPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirPartidaActionPerformed(evt);
            }
        });

        tirarCañas.setBackground(new java.awt.Color(204, 255, 255));
        tirarCañas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tirarCañas.setForeground(new java.awt.Color(102, 51, 0));
        tirarCañas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dados.png"))); // NOI18N
        tirarCañas.setText("Tirar Cañas");
        tirarCañas.setEnabled(false);
        tirarCañas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        tirarCañas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirarCañasActionPerformed(evt);
            }
        });

        empezarPartida.setBackground(new java.awt.Color(204, 255, 255));
        empezarPartida.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        empezarPartida.setForeground(new java.awt.Color(102, 51, 0));
        empezarPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/start.png"))); // NOI18N
        empezarPartida.setText("Empezar Partida");
        empezarPartida.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        empezarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarPartidaActionPerformed(evt);
            }
        });

        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Obtuviste:");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Monto Actual:");

        txtMontoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoAActionPerformed(evt);
            }
        });

        nombreJugador.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(17, 17, 17)
                                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(tirarCañas))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb1)
                                    .addComponent(jLabel1)
                                    .addComponent(lb3))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb2)
                                    .addComponent(lb4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(lb5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btnSalirPartida))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(txtMontoA, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addComponent(empezarPartida)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(120, 120, 120)
                        .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(649, 649, 649)
                    .addComponent(jLabel2)
                    .addContainerGap(712, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(tirarCañas)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMontoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(empezarPartida)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalirPartida))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(420, 420, 420)
                    .addComponent(jLabel2)
                    .addContainerGap(453, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método oyente que llama al método salirPartida   
     *
     * @param evt: Evento al que escucha.
     */
    private void btnSalirPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirPartidaActionPerformed
        // TODO add your handling code here:
        menuP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirPartidaActionPerformed
    
    /**
    *Método que habilita la opción de tirar cañas.
    *@param evt: Evento al que escucha. 
    */
    private void empezarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarPartidaActionPerformed
        // TODO add your handling code here:
        tirarCañas.setEnabled(true); 

    }//GEN-LAST:event_empezarPartidaActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    /**
     * Método que llamada a la funcionalidad de tirarCañas en el componente de
     * Lógica y cambia los iconos respectivos.
     */
    private void tirarCañasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirarCañasActionPerformed
        // TODO add your handling code here:
        FachadaLogica fachadaL=new FachadaLogica(); 
        int caña1=0, caña2=0, caña3=0, caña4=0, caña5=0, resultado=0; 
        int[] arreglo= new int[6];
        arreglo[0]= caña1;
        arreglo[1]= caña2;
        arreglo[2]= caña3; 
        arreglo[3]= caña4;
        arreglo[4]= caña5;
        arreglo[5]= resultado;
        int[] arreglo2= fachadaL.tirarCañas(arreglo);
        txtResultado.setText(""+arreglo2[5]);
        Icon uno= new javax.swing.ImageIcon(getClass().getResource("/img/caña 2.png")); 
        Icon cero= new javax.swing.ImageIcon(getClass().getResource("/img/Caña 1.png"));

        if(arreglo2[0]==0){
           lb1.setIcon(cero);
        }
        if(arreglo2[1]==0){
           lb2.setIcon(cero);
        }
        if(arreglo2[2]==0){
           lb3.setIcon(cero);
        }
        if(arreglo2[3]==0){
           lb4.setIcon(cero);
        }
        if(arreglo2[4]==0){
           lb5.setIcon(cero);
        }
      if(arreglo2[0]==1){
            lb1.setIcon(uno);
        }
        if(arreglo2[1]==1){
            lb2.setIcon(uno);
        }
        if(arreglo2[2]==1){
            lb3.setIcon(uno);
        } 
        if(arreglo2[3]==1){
            lb4.setIcon(uno);
        } 
        if(arreglo2[4]==1){
            lb5.setIcon(uno);
        }
    }//GEN-LAST:event_tirarCañasActionPerformed

    private void txtMontoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirPartida;
    private javax.swing.JButton empezarPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel nombreJugador;
    private javax.swing.JPanel panelTablero;
    private javax.swing.JButton tirarCañas;
    public javax.swing.JTextField txtMontoA;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables


}
